version: "3"
services:
  nginx:
    build: ./nginx
    container_name: pb_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    links:
      - web

  postgres:
    image: postgres
    container_name: pb_postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/app/data
    environment:
      - PGDATA=/app/data
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build: .
    container_name: pb_web
    command: bash -c "python manage.py collectstatic --noinput && uwsgi --ini /app/pharm_bricks.ini"
    volumes:
     - .:/app
     - ./static:/app/static
    ports:
      - 8001:8001
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - EMAIL_SENDER_EMAIL
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
      - ADMIN_EMAIL
      - HOSTNAME
      - SECRET_KEY
      - ALLOWED_HOST

volumes:
  dbdata:
