version: "3"
services:
  pb_nginx:
    image: nginx
    container_name: pb_nginx
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pb_app

  pb_postgres:
    image: postgres
    container_name: pb_postgres
    restart: always
    volumes:
      - .:/app
    environment:
      - PGDATA=/app/data/pg_data
      - POSTGRES_DB=pharm_bricks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
