# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('news', '0002_auto_20171220_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
