# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 06:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180830_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(),
            preserve_default=False,
        ),
    ]
