# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'core', '0001_initial'), (b'core', '0002_pharmbrickssettings_footer')]

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmBricksSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('footer', models.TextField(blank=True, default=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
