# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181117_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmbrickssettings',
            name='address',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='pharmbrickssettings',
            name='linkedin_link',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='pharmbrickssettings',
            name='twitter_link',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
