# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0006_auto_20180208_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=128, verbose_name='organization'),
        ),
    ]
