# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180625_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_on_news',
            field=models.BooleanField(default=False),
        ),
    ]
