# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180831_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
