# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('catalogue_number', models.CharField(max_length=20, verbose_name='Catalogue number')),
                ('log_p', models.FloatField(blank=True, null=True, verbose_name='Log P')),
                ('log_d', models.FloatField(blank=True, null=True, verbose_name='Log D')),
                ('log_s', models.FloatField(blank=True, null=True, verbose_name='Log S')),
                ('mw', models.FloatField(blank=True, null=True, verbose_name='MW')),
                ('cas', models.CharField(blank=True, max_length=50, null=True)),
                ('purity', models.IntegerField(blank=True, null=True)),
                ('salt', models.CharField(blank=True, max_length=20, null=True)),
                ('chemical_name', models.CharField(max_length=150)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MoleculePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=32, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mols.Molecule')),
            ],
        ),
        migrations.CreateModel(
            name='MoleculesGroup',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
