# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import mols.models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0002_auto_20180311_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='image',
            field=models.ImageField(null=True, upload_to=mols.models.mol_image_path),
        ),
    ]
