# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0003_auto_20180311_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecule',
            name='log_d',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='salt',
        ),
        migrations.AddField(
            model_name='molecule',
            name='formula',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='molecule',
            name='chemical_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='log_p',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Log P, calc'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='log_s',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Log S, calc'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='mw',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Mass'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='purity',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Chemical purity'),
        ),
    ]
