# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import mols.models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0004_auto_20180512_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mols.models.mol_image_path),
        ),
    ]
