# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import mols.models
import mols.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0005_auto_20180513_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=mols.storage.OverwriteStorage(), upload_to=mols.models.mol_image_path),
        ),
    ]
