# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('mols', '0006_auto_20180513_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link_external', models.URLField(max_length=510, verbose_name=b'External link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='molecule',
            name='msds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='screening_compounds',
            field=models.ManyToManyField(blank=True, null=True, related_name='_molecule_screening_compounds_+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='moleculereference',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='mols.Molecule'),
        ),
    ]
