# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0007_auto_20180708_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='screening_compounds',
            field=models.ManyToManyField(related_name='_molecule_screening_compounds_+', to='wagtaildocs.Document'),
        ),
    ]
