# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0008_auto_20180708_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculereference',
            name='link_external',
        ),
        migrations.AddField(
            model_name='moleculereference',
            name='link',
            field=models.URLField(max_length=510, verbose_name=b'Link'),
            preserve_default=False,
        ),
    ]
