# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 23:16
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('mols', '0011_auto_20180708_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculescreeningcompound',
            name='document',
        ),
        migrations.RemoveField(
            model_name='moleculescreeningcompound',
            name='page',
        ),
        migrations.AddField(
            model_name='molecule',
            name='screening_compounds',
            field=modelcluster.fields.ParentalManyToManyField(related_name='_molecule_screening_compounds_+', to='wagtaildocs.Document'),
        ),
        migrations.DeleteModel(
            name='MoleculeScreeningCompound',
        ),
    ]
