# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('mols', '0012_auto_20180708_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecule',
            name='screening_compounds',
        ),
    ]
