# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0013_auto_20180708_2323'),
    ]

    operations = [
    ]
