# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0015_moleculescreeningcompound'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moleculesgroup',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='moleculesgroup',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='moleculesgroup',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
