# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('mols', '0016_auto_20180710_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moleculesgroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='moleculesgroup',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='moleculesgroup',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
