# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0017_auto_20180711_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculesgroup',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
