# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0018_moleculesgroup_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moleculeprices',
            options={'ordering': ('price',)},
        ),
    ]
