# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0019_auto_20180820_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculeprices',
            name='product',
        ),
    ]
