# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0020_remove_moleculeprices_product'),
        ('shop', '0004_auto_20180823_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoleculePrices',
        ),
    ]
