# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mols', '0021_delete_moleculeprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='smiles',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
