# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-06 13:14
from __future__ import unicode_literals

import bookmarks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bookmarks', '0002_generatorresultbookmark'), ('bookmarks', '0003_auto_20181002_1821'), ('bookmarks', '0004_auto_20181003_0630'), ('bookmarks', '0005_auto_20181003_0756'), ('bookmarks', '0006_auto_20181003_1736')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorResultBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=bookmarks.models.generator_result_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='productbookmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='generatorresultbookmark',
            unique_together=set([('file', 'user')]),
        ),
        migrations.AlterField(
            model_name='generatorresultbookmark',
            name='file',
            field=models.FileField(null=True, upload_to=bookmarks.models.generator_result_path),
        ),
    ]
