# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_generatorresultbookmark_squashed_0006_auto_20181003_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorresultbookmark',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbookmark',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
