# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import shop.models


class Migration(migrations.Migration):

    replaces = [('shop', '0001_initial'), ('shop', '0002_auto_20180819_1635'), ('shop', '0003_auto_20180820_0808'), ('shop', '0004_auto_20180823_0803')]

    dependencies = [
        # ('mols', '0018_moleculesgroup_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('ref', models.CharField(max_length=32, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('product',
                 modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='prices', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=shop.models.order_number, editable=False, max_length=8, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Finished'), (3, 'Cancelled')], default=1)),
                ('status_note', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=128)),
                ('delivery_address', models.CharField(max_length=500)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductVariant')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
