# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-29 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial_squashed_0004_auto_20180823_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('id',)},
        ),
    ]
