# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('screening_libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBlockType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='buildingblock',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='buildingblock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='buildingblock',
            name='reagents_title',
        ),
        migrations.AddField(
            model_name='buildingblock',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
