# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening_libraries', '0003_auto_20180821_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeninglibrariyprices',
            name='product',
        ),
        migrations.DeleteModel(
            name='ScreeningLibrariyPrices',
        ),
    ]
