# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_libraries', '0004_auto_20180823_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeninglibrary',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
