# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 00:51
from __future__ import unicode_literals

import core.fields
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('screening_libraries', '0005_screeninglibrary_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeninglibrary',
            name='detail_description',
            field=wagtail.wagtailcore.fields.StreamField([(b'h2', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'h3', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon=b'pilcrow', required=False)), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'alignment', core.fields.ImageFormatBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))], icon=b'image', label='Aligned image', required=False)), (b'video', wagtail.wagtailcore.blocks.StructBlock([(b'video_link', wagtail.wagtailembeds.blocks.EmbedBlock())], icon=b'media', label='Embedded video', required=False)), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock(required=False))], null=True),
        ),
        migrations.AlterField(
            model_name='screeninglibrary',
            name='preview_description',
            field=wagtail.wagtailcore.fields.StreamField([(b'h2', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'h3', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon=b'pilcrow', required=False)), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'alignment', core.fields.ImageFormatBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))], icon=b'image', label='Aligned image', required=False)), (b'video', wagtail.wagtailcore.blocks.StructBlock([(b'video_link', wagtail.wagtailembeds.blocks.EmbedBlock())], icon=b'media', label='Embedded video', required=False)), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock(required=False))], null=True),
        ),
    ]
