# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtaildocs', '0007_merge'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('shop', '0001_initial_squashed_0004_auto_20180823_0803'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('screening_libraries', '0007_auto_20180826_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingblocktype',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='buildingblock',
            name='reagents',
            field=models.ManyToManyField(blank=True, null=True, related_name='building_block', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='sdf_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_block_model', to='wagtaildocs.Document'),
        ),
        migrations.DeleteModel(
            name='BuildingBlockType',
        ),
    ]
