# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('screening_libraries', '0008_auto_20180826_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBlockReagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='buildingblock',
            name='reagents',
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='sdf_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='buildingblockreagent',
            name='building_block',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='screening_libraries.BuildingBlock'),
        ),
        migrations.AddField(
            model_name='buildingblockreagent',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
    ]
