# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening_libraries', '0009_auto_20180826_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingblock',
            name='sdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='buildingblockreagent',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
    ]
