# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('screening_libraries', '0010_auto_20180826_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='buildingblockreagent',
            name='building_block',
        ),
        migrations.RemoveField(
            model_name='buildingblockreagent',
            name='file',
        ),
        migrations.RemoveField(
            model_name='buildingblock',
            name='sdf_file',
        ),
        migrations.DeleteModel(
            name='BuildingBlockReagent',
        ),
        migrations.AddField(
            model_name='reaction',
            name='building_block',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='screening_libraries.BuildingBlock'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reactant_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactant_files', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_files', to='wagtaildocs.Document'),
        ),
    ]
