# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_libraries', '0011_auto_20180929_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='screeninglibrary',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='reaction',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
