# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_libraries', '0012_auto_20181023_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeninglibrary',
            name='preview_description',
            field=models.TextField(null=True),
        ),
    ]
