# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 23:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks
import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0003_auto_20180619_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'h2', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'h3', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon=b'pilcrow', required=False)), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'alignment', core.fields.ImageFormatBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))], icon=b'image', label='Aligned image', required=False)), (b'video', wagtail.wagtailcore.blocks.StructBlock([(b'video_link', wagtail.wagtailembeds.blocks.EmbedBlock())], icon=b'media', label='Embedded video', required=False)), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock(required=False))], blank=True, null=True),
        ),
    ]
