# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 22:15
from __future__ import unicode_literals

import core.fields
import core.storage
from django.db import migrations, models
import django.db.models.deletion
import static_page.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    replaces = [(b'static_page', '0006_homepage'), (b'static_page', '0007_homeslider'), (b'static_page', '0008_homeslider_image')]

    dependencies = [
        ('static_page', '0005_auto_20180620_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('staticpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='static_page.StaticPage')),
                ('footer', wagtail.wagtailcore.fields.StreamField([(b'h2', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'h3', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon=b'pilcrow', required=False)), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'alignment', core.fields.ImageFormatBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))], icon=b'image', label='Aligned image', required=False)), (b'video', wagtail.wagtailcore.blocks.StructBlock([(b'video_link', wagtail.wagtailembeds.blocks.EmbedBlock())], icon=b'media', label='Embedded video', required=False)), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock(required=False))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('static_page.staticpage',),
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('staticpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='static_page.StaticPage')),
                ('image', models.ImageField(blank=True, null=True, storage=core.storage.OverwriteStorage(), upload_to=static_page.models.slider_image_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('static_page.staticpage',),
        ),
    ]
