# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0006_homepage_squashed_0008_homeslider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='footer',
        ),
    ]
